### ISSUE TITLE
using ? causes error

### ISSUE THREAD

**Issue by egh** [chumpage/mag-menu#5]
When running the example code:

```
(mag-menu
   `(group-name
     (man-page "man-page")
     (actions
      ("r" "Run the command" action-callback))
     (switches
      ("-b" "Some on/off option" "--long-form-option-name" switch-callback))
     (arguments
      ("-f" "Some option that takes a value" "--value=" arg-callback history-var))))
```

typing `?` causes the following error:

```
funcall-interactively: Symbol's value as variable is void: group
```

This is emacs 25.0.50.1 on ubuntu.

**Comment by chumpage** [comment]
I need to declare lexical-binding in the first line of the file. Using a local variable list at the end of the file doesn't work for lexical-binding anymore (if it ever did).

**Comment by egh** [comment]
Thanks!

**Comment by chumpage** [comment]
No prob, thanks for the bug report.
